#pragma once

#define IDD_IMAGE_BINARIZE_BOX                  102
#define IDC_IMAGE_BINARIZE_THRESHOLD_EDIT       103

#define IDD_IMAGE_LINEAR_STRETCH_BOX            104
#define IDD_IMAGE_LINEAR_STRETCH_SRC1_EDIT      105
#define IDD_IMAGE_LINEAR_STRETCH_TARGET1_EDIT   106
#define IDD_IMAGE_LINEAR_STRETCH_SRC2_EDIT      107
#define IDD_IMAGE_LINEAR_STRETCH_TARGET2_EDIT   108

#define IDD_IMAGE_LOG_STRETCH_BOX               109
#define IDD_IMAGE_LOG_STRETCH_A_EDIT            110
#define IDD_IMAGE_LOG_STRETCH_B_EDIT            111
#define IDD_IMAGE_LOG_STRETCH_C_EDIT            112

#define IDD_IMAGE_EXPONENTIAL_STRETCH_BOX       113
#define IDD_IMAGE_EXPONENTIAL_STRETCH_A_EDIT    114
#define IDD_IMAGE_EXPONENTIAL_STRETCH_B_EDIT    115
#define IDD_IMAGE_EXPONENTIAL_STRETCH_C_EDIT    116

#ifndef IDC_STATIC
#define IDC_STATIC                              -1
#endif

